server:
  port: 8765
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-products
          uri: lb://PRODUCTS
          predicates:
          - Path=/products/**
            
        
             